CI_HOSTNAME: lmb-ci-server
CI_IP: 192.168.50.4
UCD_HOSTNAME: lmb-ucd-server
UCD_IP: 192.168.50.5
CLM_HOSTNAME: lmb-clm-server
CLM_IP: 192.168.50.6
GIT_HOSTNAME: lmb-git-server
GIT_IP: 192.168.50.7
STASH_HOSTNAME: lmb-stash-server
STASH_IP: 192.168.50.8
GITHUB_HOSTNAME: lmb-github-server
GITHUB_IP: 192.168.50.9
RRDI_HOSTNAME: lmb-rrdi-server
RRDI_IP: 192.168.50.10
DB_HOSTNAME: lmb-db-server
DB_IP: 192.168.50.11
AGENT1_HOSTNAME: lmb-agent1-server
AGENT1_IP: 192.168.50.12
AGENT2_HOSTNAME: lmb-agent2-server
AGENT2_IP: 192.168.50.13
UCR_HOSTNAME: lmb-ucr-server
UCR_IP: 192.168.50.14
RLIA_HOSTNAME: lmb-rlia-server
RLIA_IP: 192.168.50.15
UCDwP_HOSTNAME: lmb-ucdwp-server
UCDwP_IP: 192.168.50.16
ANSIBLE_HOSTNAME: lmb-ansible-server
ANSIBLE_IP: 192.168.50.17
VAGRANT_PROVIDER: virtualbox
