name             'SYNC'
maintainer       'Liora Milbaum'
maintainer_email 'liora@lmb.co.il'
license          'MIT'
description      'Tasktop Sync'
long_description 'Tasktop Sync'
version          '0.0.1'
